In [2]:
import duckdb

In [3]:
con = duckdb.connect("olist.duckdb")   # creates the database file

In [4]:
files = {
    "customers": "olist_customers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "order_payments": "olist_order_payments_dataset.csv",
    "order_reviews": "olist_order_reviews_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "category_translation": "product_category_name_translation.csv",
}

In [5]:
for table, f in files.items():
    con.execute(f"CREATE OR REPLACE TABLE {table} AS SELECT * FROM read_csv_auto('data/{f}')")
    n = con.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    print(table, n)

customers 99441
geolocation 1000163
order_items 112650
order_payments 103886
order_reviews 99224
orders 99441
products 32951
sellers 3095
category_translation 71

In [6]:
con.execute("DESCRIBE orders").df()[["column_name", "column_type"]]

                     column_name column_type
0                       order_id     VARCHAR
1                    customer_id     VARCHAR
2                   order_status     VARCHAR
3       order_purchase_timestamp   TIMESTAMP
4              order_approved_at   TIMESTAMP
5   order_delivered_carrier_date   TIMESTAMP
6  order_delivered_customer_date   TIMESTAMP
7  order_estimated_delivery_date   TIMESTAMP

In [7]:
con.execute("""
SELECT
  COUNT(*) AS total_rows,
  COUNT(DISTINCT customer_id) AS unique_customer_id,
  COUNT(DISTINCT customer_unique_id) AS unique_customer_unique_id
FROM customers
""").df()

   total_rows  unique_customer_id  unique_customer_unique_id
0       99441               99441                      96096

In [8]:
con.close()